[package]
name = "naskoc-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nasko_proc_macro = { path = "../nasko_proc_macro" }
logos = "0.12.0"
transmute = "0.1.1"
